Milestone 1: Getting started
SamroodAli/react-calculator pull request #1
Opened 2021-09-03 10:29 UTC by SamroodAli

I created a react app using `create-react-app` to start the calculator app
- [ ]  Added dependencies `Big.js` and `propTypes`
- [ ] Added github actions and linters
- [ ] Deployed to heroku and is available [here](https://samrood-calculator.herokuapp.com/)
Please review my code.
Thanks for your time and consideration.

2021-09-03 10:48 UTC, rindrajosia requested changes
Hi, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Please, make sure that linter checks are not failing.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-09-03 10:51 UTC, rindrajosia commented on src/index.js
> +import 'app.css';
Please check this line. it should be ` import './app.css' `. That the reason why you cannot deploy your APP.

2021-09-03 11:29 UTC, SamroodAli commented
Thank you @rindrajosia for reviewing my code. The import css file was causing a problem. Thanks for solving that.
I am requesting another code review.

2021-09-03 11:45 UTC, rindrajosia requested changes
Hi, 

Good job so far!
There are some issues to revise before continuing to the next project but hang in there and read the comments below with care. You can do it! :muscle:


## Required Changes ♻️

- [ ] Unnecessary files or assets, such as the React svg Logo, should be deleted.
([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone1/files-removed.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896085/)). Please check the public folder because logo512.png is still present there.

- [ ] Please make sure that provide correct information in your readme file. Keep in mind that it is the first thing users check.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-09-03 11:45 UTC, rindrajosia commented on README.md
> +This project is [MIT](lic.url) licensed.
- [ ] [REQUIRED] This link is broken, please fix it

2021-09-03 11:45 UTC, rindrajosia commented on README.md
> +  $ git clone https://github.com/SamroodAli/books-library.git
- [ ] [REQUIRED] I think, this should be: $ git clone https://github.com/SamroodAli/react-calculator.git

2021-09-03 11:45 UTC, rindrajosia commented on README.md
> +Feel free to check the [issues page](issues/).
- [ ] [REQUIRED] The issue link is broken. Please fix it.

2021-09-03 14:27 UTC, oloomoses approved these changes
Hi @SamroodAli, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-06 07:56 UTC, SamroodAli commented
Thanks @oloomoses  for reviewing my code.

2021-09-06 07:56 UTC, merged